"""empty message

Revision ID: 430d32d1bb8f
Revises: 
Create Date: 2019-05-19 15:25:21.664953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430d32d1bb8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('online', sa.DateTime(), nullable=True),
    sa.Column('numVotes', sa.Integer(), nullable=True),
    sa.Column('numReviews', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_index(op.f('ix_user_online'), 'user', ['online'], unique=False)
    op.create_index(op.f('ix_user_permissions'), 'user', ['permissions'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_permissions'), table_name='user')
    op.drop_index(op.f('ix_user_online'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
