"""empty message

Revision ID: 7dd891ac6c27
Revises: 
Create Date: 2019-05-18 23:57:16.272842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd891ac6c27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.NullType(), nullable=True),
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('email', sa.NullType(), nullable=True),
    sa.Column('password_hash', sa.NullType(), nullable=True),
    sa.Column('online', sa.NullType(), nullable=True),
    sa.Column('numVotes', sa.NullType(), nullable=True),
    sa.Column('numReviews', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
